#!/bin/bash

killall "VLC"
nohup "/Applications/VLC.app/Contents/MacOS/VLC" --fullscreen --loop "/Users/ooftv/Movies/ooftv/playlists/today.m3u" &>/dev/null &

echo "New playlist made: " >>/tmp/restartstream.log
date >> /tmp/restartstream.log
