#!/bin/bash

# probably better to run the command as a launchdaemon, have it automatically respawn

#sleep 120s
killall "VLC"
whoami 
echo "Stream Restarted: "
date
"/Applications/VLC.app/Contents/MacOS/VLC" --fullscreen --loop "/Users/ooftv/Movies/ooftv/playlists/today.m3u"
